name: CI-CD


on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.11.1
              uses: actions/setup-node@v4
              with:
                node-version: '20.11.1'

            - name: Install dependencies
              run: npm i

            - name: Run unit tests
              run: npm run test:unit